### ISSUE TITLE
Caching API improvements

### ISSUE THREAD

**Issue by spacedmonkey** [ymirapp/wordpress-plugin#10]
There have been a number of improves to the core caching api. See
https://make.wordpress.org/core/2022/04/29/caching-improvements-in-wordpress-6-0/
https://make.wordpress.org/core/2022/10/11/performance-field-guide-for-wordpress-6-1/

The ones I would highlight for you are the following. 
- wp_cache_supports - Simple to implement
- wp_cache_flush_runtime- Simple to implement
- wp_cache_flush_group - Harder to implement.

**Comment by carlalexander** [comment]
Heya friend! 💖

The Ymir plugin itself doesn't do any sort of cache interactions. I used to have a DynamoDB object cache, but I removed it as well as all the object cache code. It's all Till's Redis plugins now.

Is there anything that doesn't deal with caching that I need to look into? I looked at the 6.1 changes and couldn't see anything that stood out :)

**Comment by spacedmonkey** [comment]
@carlalexander I saw [this](https://github.com/ymirapp/wordpress-plugin/blob/033ea5ad6497ec49bcae4924c8446c05feb6f987/object-cache-api.php#L126-L131) in your plugin. So I thought you were implementing an object cache. Is that not the case? 

If you do, the above, are just simple functions that add better compatibility with core.

**Comment by carlalexander** [comment]
@spacedmonkey that's an oversight. I should have deleted that file 🤣
